spring:
  application:
    name: urbanly
  datasource:
    url: jdbc:postgresql://localhost:5432/urbanly_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use validate ou none em produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
secret:
  key: "bG9yZW0gbG9yZW0gYXNoeWFoc2FiYyBhb3NqYW9zamFvLWl0aWFqc2lhanNhLW1zYW9za2Fvc2EtMWE="